language: php
dist: precise
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - composer install

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_cache:
  - rm -f $HOME/.composer/cache
